name: "demo-action"
on:
  workflow_dispatch:
  push: 
    branches: ["main"]
permissions: 
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
           node-version: 18
           cache: 'pnpm'
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
